//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wko.BabyTracker.Globals {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationLabels {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationLabels() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Wko.BabyTracker.Globals.ApplicationLabels", typeof(ApplicationLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Timeline_Title_Feeding {
            get {
                return ResourceManager.GetString("Timeline_Title_Feeding", resourceCulture);
            }
        }
        
        internal static string Timeline_Title_Sleep {
            get {
                return ResourceManager.GetString("Timeline_Title_Sleep", resourceCulture);
            }
        }
        
        internal static string Timeline_Title_Measure_Circumference {
            get {
                return ResourceManager.GetString("Timeline_Title_Measure_Circumference", resourceCulture);
            }
        }
        
        internal static string Timeline_Title_Milestone {
            get {
                return ResourceManager.GetString("Timeline_Title_Milestone", resourceCulture);
            }
        }
        
        internal static string Timeline_Title_NappyChange {
            get {
                return ResourceManager.GetString("Timeline_Title_NappyChange", resourceCulture);
            }
        }
        
        internal static string Timeline_Title_Measure_Size {
            get {
                return ResourceManager.GetString("Timeline_Title_Measure_Size", resourceCulture);
            }
        }
        
        internal static string Timeline_Title_Measure_Weight {
            get {
                return ResourceManager.GetString("Timeline_Title_Measure_Weight", resourceCulture);
            }
        }
        
        internal static string Timeline_Title_Measure_Temperature {
            get {
                return ResourceManager.GetString("Timeline_Title_Measure_Temperature", resourceCulture);
            }
        }
        
        internal static string Timeline_Title_Default {
            get {
                return ResourceManager.GetString("Timeline_Title_Default", resourceCulture);
            }
        }
    }
}
